Extract the access_token property from the response JSON

diff --git a/hooks/pre-command b/hooks/pre-command
--- a/hooks/pre-command
+++ b/hooks/pre-command
@@ -44,7 +44,9 @@ if [ -z "${PULUMI_TOKEN_TYPE:-}" ] || [ -z "${PULUMI_TOKEN_SCOPE:-}" ]; then
     exit 1
 fi
 
-pul_access_token=$(curl -X POST  \
+echo "Requesting Pulumi access token using OIDC token exchange method..."
+
+json=$(curl -X POST  \
         -H "Content-Type: application/x-www-form-urlencoded" \
         -d "audience=$OIDC_AUDIENCE" \
         -d "grant_type=urn:ietf:params:oauth:grant-type:token-exchange" \
@@ -53,6 +55,13 @@ pul_access_token=$(curl -X POST  \
         -d "scope=$PULUMI_TOKEN_SCOPE" \
         -d "subject_token=$bk_token" \
         https://api.pulumi.com/api/oauth/token)
+
+if [ -z "${json:-}" ]; then
+    echo "❌ Error acquiring Pulumi access token using OIDC token exchange method."
+    exit 1
+fi
+
+pul_access_token=$(echo $json | jq '.access_token')
 
 PULUMI_ACCESS_TOKEN=$pul_access_token pulumi login "${BACKEND_URL}"
 
